### PR TITLE
[refactor] De-conflict-ify the package annotation in Java.

### LINKED ISSUE #34: Package metadata field is problematic in Java
The current field name of `package` for product metadata on the `input-contract` branch is problematic for Java/Kotlin because protoc does not check for reserved keywords.

https://github.com/googleapis/api-common-protos/blob/3f5a16b2c94a60a1aeb5424d490e62e3a69485ba/google/api/client.proto#L89

Can we change the name before it goes mainstream? I did open a PR for an upstream fix, but changing the name is probably easier (maybe `package_metadata`?): https://github.com/protocolbuffers/protobuf/pull/5709

cc/ @noahdietz @timburks - I'll update kiosk once this is resolved.

### PR DESCRIPTION
**Pull request by lukesneeringer**
Fixes #34.

### CODE REVIEW

**Comment by jbolinger** [comment]
This does indeed resolve the package problem, but what happened to the LRO annotations?

I tried to update but cannot find them on this branch. Where did they move to?

**Comment by andreamlin** [comment]
@lukesneeringer Can you answer the above?

**Comment by noahdietz** [comment]
Which annotations are we referring to? The `operation_metadata` ones? Because they were moved to `operation_info` here: https://github.com/googleapis/api-common-protos/blob/input-contract/google/longrunning/operations.proto#L173-L202

**Comment by jbolinger** [comment]
I can't remember, but that may be the one. I'll try to update again.

**Comment by lukesneeringer** [comment]
Sorry for not seeing this. The LRO annotations are at `google.longrunning.OperationInfo` (the message) and `google.longrunning.operation_info` (the method annotation).

**Comment by jbolinger** [comment]
Got it - I was able to update successfully. Thanks folks!

**Pull request merged**
